# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Seoul

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

# Site metadata
title: 개발일지 # the main title
tagline: 개발을 공부하고 있어요. # it will display as the subtitle
description: >-
  hayeonkimmie 블로그 | 풀스택 개발, AI, 데이터분석에 관심있습니다.

# Fill in the protocol & hostname for your site.
url: "https://hayeonkimmie.github.io"

github:
  username: hayeonkimmie

twitter:
  username: hayeonkimmie

social:
  name: Hayeon Kim
  email: hayeonkimmie@gmail.com
  links:
    - https://twitter.com/hayeonkimmie
    - https://github.com/hayeonkimmie

# Site Verification Settings
webmaster_verifications:
  google: ""
  bing: ""
  alexa: ""
  yandex: ""
  baidu: ""
  facebook: ""

# Web Analytics Settings
analytics:
  google:
    id: ""
  goatcounter:
    id: ""
  umami:
    id: ""
    domain: ""
  matomo:
    id: ""
    domain: ""
  cloudflare:
    id: ""
  fathom:
    id: ""

# Page views settings
pageviews:
  provider: ""

# Prefer color scheme setting
theme_mode: ""

# CDN settings
cdn: "https://chirpy-img.netlify.app"

# Avatar settings
avatar: "/commons/avatar.jpg"

# Social preview image
social_preview_image: ""

# Table of Contents
toc: true

# Comments settings
comments:
  provider: utterances
  utterances:
    repo: hayeonkimmie/hayeonkimmie.github.io
    issue_term: title
    label: "comments"
    theme: github-light
    follow_site_theme: true

# Self-hosted static assets
assets:
  self_host:
    enabled: false
    env: ""

# PWA settings
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

# Pagination
paginate: 10

# Base URL
baseurl: ""

# Markdown and Syntax Highlighting
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
